#/bin/bash
#PBS -N plink
#PBS -l nodes=1:ppn=8
#PBS -e clump_5e8.err
#PBS -o clump_5e8.log
#PBS -q batch
#PBS -V


### set arguments

plink="/mnt/d/plink"
ref_file="/mnt/e/move/disk_document/Projects_documents/05.allergic_diseases_mental_disorders/01.allergic_diseases_anxiety/reference/g1000_eur"  ###参考文件要单独放一个文件夹
p1="0.000005"
p2="1"
r2="0.1"
kb="1000"

molecules_dir='/mnt/e/move/disk_document/Projects_documents/05.allergic_diseases_mental_disorders/01.allergic_diseases_anxiety/data/clean_data/clean_data_GRCh37/19molecules'
bladder_dir="/mnt/e/Extra_money(work)/No.5_customer/data/bladder_problem_5e6"

result_dir="/mnt/e/move/disk_document/Projects_documents/05.allergic_diseases_mental_disorders/01.allergic_diseases_anxiety/data/clean_data/clump_result/02.p5e6"

cd ${molecules_dir}
traits_molecules=`ls *.clean.txt | cut -d '.' -f 1`

cd ${bladder_dir}
traits_bladder=`ls *.clean.txt | cut -d '.' -f 1`


### perform LD clumping in plink

for i in ${traits_molecules[@]}; do
	${plink}/plink \
		--bfile ${ref_file}/g1000_eur \
		--clump-snp-field rsid \
		--clump-field p \
		--clump-p1 ${p1} \
		--clump-p2 ${p2} \
		--clump-r2 ${r2} \
		--clump-kb ${kb} \
		--clump ${molecules_dir}/${i}.clean.txt \
		--out ${result_dir}/${i}.LD_result
done

for j in ${traits_bladder[@]}; do
	${plink}/plink \
		--bfile ${ref_file}/g1000_eur \
		--clump-snp-field rsid \
		--clump-field p \
		--clump-p1 ${p1} \
		--clump-p2 ${p2} \
		--clump-r2 ${r2} \
		--clump-kb ${kb} \
		--clump ${bladder_dir}/${j}.clean.txt \
		--out ${result_dir}/${j}.LD_result
done
###############################该脚本旨在对clean.txt文件中的snp进行进一步筛选，取p<5e-6,r2<0.1,kb=1000的SNP