#!/bin/bash
#PBS -S /bin/bash
#PBS -N mixer
#PBS -l nodes=cu06:ppn=16
#PBS -e mixer.err
#PBS -o mixer.log
#PBS -q batch
#PBS -V

export OMP_NUM_THREADS=16
export OPENBLAS_NUM_THREADS=16
export MKL_NUM_THREADS=16
export VECLIB_MAXIMUM_THREADS=16
export NUMEXPR_NUM_THREADS=16

#cd $PBS_O_WORKDIR
source /public/jiangjw/miniconda3/bin/activate poly_genic_overlap

#Anxiety=("anxiety2021")
#Allergic_disease=("ADE2021" "ADE2015" "AR_Diagnose" "AR_SelfReport" "Asthma2020" "Asthma2018")
Allergic_disease=("BAD")
sumstats_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/python_convert-master'
data_dir='/public/jiangjw/02.anxiety_ADs/data'
result_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/data'

#############################input preparation####################################
#first step			
#for i in ${Anxiety[@]}
#do
#        python3.7 ${sumstats_dir}/sumstats.py csv \
#        --sumstats ${data_dir}/Anxiety/${i}.clean.txt \
#        --out ${result_dir}/${i}.clean.csv \
#        --force --auto --n N
#done

#for i in ${Allergic_disease[@]}
#do
#	python3.7 ${sumstats_dir}/sumstats.py csv \
#        --sumstats ${data_dir}/Allergic_diseases/${i}.clean.txt \
#        --out ${result_dir}/${i}.clean.csv \
#        --force --auto --n N
#done

#second step
#cd ${result_dir}
#inputs=`ls BAD.clean.csv | cut -d '.' -f 1`
#for i in ${inputs[@]}
#do
#	python3.7 ${sumstats_dir}/sumstats.py zscore --sumstats ./${i}.clean.csv | \
#	python3.7 ${sumstats_dir}/sumstats.py qc --exclude-ranges 6:26000000-34000000 --max-or 1e37 | \
#	python3.7 ${sumstats_dir}/sumstats.py neff --drop --factor 4 --out ./${i}_qc_noMHC.clean.csv --force
#	gzip ./${i}_qc_noMHC.clean.csv
#done
#csv: load summary data and convert it into a standardized format
#sumstats: input gwas summary data,force: cover previous result, auto: auto detecting relative column  
#calculating z-score from p-value and effect size(OR,BETA etc.)
#exclude-ranges: exclude chr:from to, max-or: exclude SNPs with OR above 1e37 and below 1/1e37
#.generate N column from NCASE and NCONTROL, as 4 / (1 /NCASE + 1 / NCONTROL)
#drop: Drop NCASE and NCONTROL columns, factor: Factor in the numerator of the NEFF formula. Default to 4. Sometimes you may want FACTOR=2. Set FACTOR=0 if you want NEFF = NCASE + NCONTROL.

######################################Univariate analysis###############################
#Fit the model
mixer_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/mixer/src/build/precimed'
uniresult_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/1.univariate_result'
reference_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/reference'
lib_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/mixer/src/build/lib'
#for i in ${Anxiety[@]}
#do
#	python3.7 ${mixer_dir}/mixer.py fit1 \
#	--trait1-file ${result_dir}/${i}_qc_noMHC.clean.csv.gz \
#	--out ${uniresult_dir}/${i}_qc_noMHC.fit.rep1 \
#	--bim-file ${reference_dir}/1000G.EUR.QC.@.bim \
#	--ld-file ${reference_dir}/1000G.EUR.QC.@.run4.ld \
#	--lib ${lib_dir}/libbgmg.so
#done

#for j in ${Allergic_disease[@]}
#do
#        python3.7 ${mixer_dir}/mixer.py fit1 \
#        --trait1-file ${result_dir}/${j}_qc_noMHC.clean.csv.gz \
#        --out ${uniresult_dir}/${j}_qc_noMHC.fit.rep1 \
#        --bim-file ${reference_dir}/1000G.EUR.QC.@.bim \
#        --ld-file ${reference_dir}/1000G.EUR.QC.@.run4.ld \
#        --lib ${lib_dir}/libbgmg.so
#done

#apply hte model to the entire set of SNPs(test model)
#for k in ${Anxiety[@]}
#do
#	python3.7 ${mixer_dir}/mixer.py test1 \
#      	--trait1-file ${result_dir}/${k}_qc_noMHC.clean.csv.gz \
#      	--load-params-file ${uniresult_dir}/$[k]_qc_noMHC.fit.rep1.json \
#      	--out ${uniresult_dir}/${k}_qc_noMHC.test.rep1 \
#      	--bim-file ${reference_dir}/1000G.EUR.QC.@.bim \
#      	--ld-file ${reference_dir}/1000G.EUR.QC.@.run4.ld \
#      	--lib ${lib_dir}/libbgmg.so
#done

#for l in ${Allergic_disease[@]}
#do
#        python3.7 ${mixer_dir}/mixer.py test1 \
#        --trait1-file ${result_dir}/${l}_qc_noMHC.clean.csv.gz \
#        --load-params-file ${uniresult_dir}/${l}_qc_noMHC.fit.rep1.json \
#        --out ${uniresult_dir}/${l}_qc_noMHC.test.rep1 \
#        --bim-file ${reference_dir}/1000G.EUR.QC.@.bim \
#        --ld-file ${reference_dir}/1000G.EUR.QC.@.run4.ld \
#        --lib ${lib_dir}/libbgmg.so
#done

#Bivariate (cross-trait) analysis----------the AIC of univariate analysis of anxiety2018 is negative, hence excluding anxiety2018 from bivariate analysis
#Anxiety_bivariate=("anxiety2021")
#biresult_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/2.bivariate_result'
#cd ${biresult_dir}
#Fit the model
#for i in ${Anxiety_bivariate[@]}
#do
#	for j in ${Allergic_disease[@]}
#	do
#		mkdir ${i}_${j}
#		python3.7 ${mixer_dir}/mixer.py fit2 \
#      		--trait1-file ${result_dir}/${i}_qc_noMHC.clean.csv.gz \
#      		--trait2-file ${result_dir}/${j}_qc_noMHC.clean.csv.gz \
#      		--trait1-params-file ${uniresult_dir}/${i}_qc_noMHC.fit.rep1.json \
#      		--trait2-params-file ${uniresult_dir}/${j}_qc_noMHC.fit.rep1.json \
#      		--out ${biresult_dir}/${i}_${j}/${i}_qc_noMHC_vs_${j}_qc_noMHC.fit.rep1 \
#      		--bim-file ${reference_dir}/1000G.EUR.QC.@.bim \
#      		--ld-file ${reference_dir}/1000G.EUR.QC.@.run4.ld \
#      		--lib ${lib_dir}/libbgmg.so
#	done
#done

#apply the model to the entire set of SNPs(test model)
for k in ${Anxiety_bivariate[@]}
do
        for l in ${Allergic_disease[@]}
        do
                python3.7 ${mixer_dir}/mixer.py test2 \
                --trait1-file ${result_dir}/${k}_qc_noMHC.clean.csv.gz \
                --trait2-file ${result_dir}/${l}_qc_noMHC.clean.csv.gz \
		--load-params-file ${biresult_dir}/${k}_${l}/${k}_qc_noMHC_vs_${l}_qc_noMHC.fit.rep1.json \
                --out ${biresult_dir}/${k}_${l}/${k}_qc_noMHC_vs_${l}_qc_noMHC.test.rep1 \
                --bim-file ${reference_dir}/1000G.EUR.QC.@.bim \
                --ld-file ${reference_dir}/1000G.EUR.QC.@.run4.ld \
                --lib ${lib_dir}/libbgmg.so
        done
done
#################################################################To visualize the result, please utilize local system(Ubuntu)###############################################

