#!/bin/bash
#PBS -S /bin/bash
#PBS -N visualize
#PBS -l nodes=cu06:ppn=16
#PBS -e visualize.err
#PBS -o visualize.log
#PBS -q batch
#PBS -V

export OMP_NUM_THREADS=16
export OPENBLAS_NUM_THREADS=16
export MKL_NUM_THREADS=16
export VECLIB_MAXIMUM_THREADS=16
export NUMEXPR_NUM_THREADS=16

#cd $PBS_O_WORKDIR
source /public/jiangjw/miniconda3/bin/activate poly_genic_overlap

uniresult_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/1.univariate_result'
run_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/mixer/src/build/precimed'
out_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/1.univariate_result/visualization'

##univariate results visualization
#traits=("anxiety2021" "ADE2021" "ADE2015" "AR_Diagnose" "AR_SelfReport" "Asthma2020" "Asthma2018")
#traits="BAD"

#for i in ${traits[@]}
#do
#	python3.7 ${run_dir}/mixer_figures.py combine \
#	--json ${uniresult_dir}/${i}_qc_noMHC.fit.rep1.json \
#	--out ${out_dir}/${i}_qc_noMHC.fit.rep1.combine

#	python3.7 ${run_dir}/mixer_figures.py one \
#	--json ${out_dir}/${i}_qc_noMHC.fit.rep1.combine.json \
#	--out ${out_dir}/${i}_qc_noMHC.fit.rep1.visualization \
#	--statistic mean std
#done

##bivariate results visualization
biresult_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/2.bivariate_result'
Anxiety=("anxiety2021")
#Allergic_disease=("ADE2021" "ADE2015" "AR_Diagnose" "AR_SelfReport" "Asthma2020" "Asthma2018")
Allergic_disease=("BAD")
visualization_dir='/public/jiangjw/01.polygenic_overlap_SWB_psyiatry20231228/01.MiXeR/2.bivariate_result/visualization'

for i in ${Anxiety[@]}
do
	for j in ${Allergic_disease[@]}
	do
		python3.7 ${run_dir}/mixer_figures.py combine \
		--json ${biresult_dir}/${i}_${j}/${i}_qc_noMHC_vs_${j}_qc_noMHC.fit.rep1.json \
		--out ${biresult_dir}/${i}_${j}/${i}_qc_noMHC_vs_${j}_qc_noMHC.fit.combine

		python3.7 ${run_dir}/mixer_figures.py combine \
		--json ${biresult_dir}/${i}_${j}/${i}_qc_noMHC_vs_${j}_qc_noMHC.test.rep1.json \
                --out ${biresult_dir}/${i}_${j}/${i}_qc_noMHC_vs_${j}_qc_noMHC.test.combine

		python3.7 ${run_dir}/mixer_figures.py two \
		--json-fit ${biresult_dir}/${i}_${j}/${i}_qc_noMHC_vs_${j}_qc_noMHC.fit.combine.json \
		--json-test ${biresult_dir}/${i}_${j}/${i}_qc_noMHC_vs_${j}_qc_noMHC.test.combine.json \
		--out ${visualization_dir}/${i}_qc_noMHC_vs_${j}_qc_noMHC.visualization \
		--statistic mean std
	done
done


