#!/bin/bash
#PBS -N SMR
#PBS -l nodes=cu02:ppn=8
#PBS -e SMR.err
#PBS -o SMR.log
#PBS -q batch
#PBS -V

summary_data_dir='/public/jiangjw/02.anxiety_ADs/09.SMR/GWAS_summary_SMR'
eQTL_dir='/public/jiangjw/02.anxiety_ADs/09.SMR/eQTL_data'
reference_dir='/public/jiangjw/02.anxiety_ADs/reference/g1000_eur'
run_dir='/public/jiangjw/02.anxiety_ADs/09.SMR/smr-1.3.1-linux-x86_64'
result_dir='/public/jiangjw/02.anxiety_ADs/09.SMR'

cd ${summary_data_dir}
#traits=("anxiety2021" "anxiety2018" "anxiety2017" "ADE2015" "ADE2021" "AR_Diagnose" "AR_SelfReport" "Asthma2020")
traits=("BAD")
tissue=("Brain_Frontal_Cortex_BA9" "Brain_Hippocampus" "WHB" "Lung" "Brain_Cortex")

for i in ${traits[@]};
do
	for j in ${tissue[@]};
	do
		${run_dir}/smr --bfile ${reference_dir}/g1000_eur --gwas-summary ${summary_data_dir}/${i}_SMR.clean.txt --beqtl-summary ${eQTL_dir}/${j} --maf 0.01 --out ${result_dir}/${i}_${j} --thread-num 10
	done
done


